POST http://localhost:3001/api/surveys/66efd75f58ddb6012bc99b82/responses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZWZkNzUyNThkZGI2MDEyYmM5OWI3OSIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3MjY5OTQyNjJ9.2gXkiKGX85pL8pdsIskhKq4BTW777n9Yz5lhVHR5R2c

{
    "questions": [
        {
            "id": "66efd75f58ddb6012bc99b7c",
            "response": "1"
        },
        {
            "id": "66efd75f58ddb6012bc99b7d",
            "response": "2"
        },
        {
            "id": "66efd75f58ddb6012bc99b7e",
            "response": "3"
        },
        {
            "id": "66efd75f58ddb6012bc99b7f",
            "response": "4"
        },
        {
            "id": "66efd75f58ddb6012bc99b80",
            "response": "5"
        },
        {
            "id": "66efd75f58ddb6012bc99b81",
            "response": "Lorem ipsum dolor sit amet"
        }
    ]
}