POST http://localhost:3001/api/surveys/66ef27d9998d8dca4771d91b/responses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZWYyZGM1ZmI4NDM3YmU0ZDJmZTM3NiIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3MjY5NTA4NTh9.nheXOYjQ025WWAZeJvcfBS_-Eo8Gd9AbRh5IKYIKb6U

{
    "questions": [
        {
            "id": "66ef27d9998d8dca4771d915",
            "response": "1"
        },
        {
            "id": "66ef27d9998d8dca4771d916",
            "response": "2"
        },
        {
            "id": "66ef27d9998d8dca4771d917",
            "response": "3"
        },
        {
            "id": "66ef27d9998d8dca4771d918",
            "response": "4"
        },
        {
            "id": "66ef27d9998d8dca4771d919",
            "response": "5"
        },
        {
            "id": "66ef27d9998d8dca4771d91a",
            "response": "Lorem ipsum dolor sit amet"
        }
    ]
}