POST http://localhost:3001/api/surveys
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZjlhOWMwOWI0NWM1OTkzZThkZGJmZCIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3Mjc2Mzc5NTZ9.WM-19Prlm2ZFtyDS7WKFbi61BEGaBL5XFkJgmvm0cIs
Content-Type: application/json

{
    "title": "Data Analysis with Python",
    "description": "Open uni: Data Analysis with Python, Online teaching",
    "questions": [
        {
            "question": "The learning objectives were clear to me.",
            "options": ["1", "2", "3", "4", "5", "N/A"]
        },
        {
            "question": "The course activities supported my learning.",
            "options": ["1", "2", "3", "4", "5", "N/A"]
        },
        {
            "question": "The course materials supported my learning.",
            "options": ["1", "2", "3", "4", "5", "N/A"]
        },
        {
            "question": "The methods used to assess the course measure my learning.",
            "options": ["1", "2", "3", "4", "5", "N/A"]
        },
        {
            "question": "The workload relative to course credits was.",
            "options": ["too heavy", "somewhat too heavy", "appropriate", "somewhat too light", "too light"]
        },
        {
            "question": "Any additional comments or suggestions.",
            "options": []
        }
    ]
}